[tools]
node = "24"
pnpm = "latest"
usage = "latest"

[env]
USERNAME = "8gau8"

[tasks.article]
description = "create a new article"
usage = '''
flag "--slug <slug>" help="slug of the article" 
'''
run = """
SLUG=${USERNAME}-{{ usage.slug }}
pnpm zenn new:article --slug $SLUG
git checkout -b "draft/$SLUG"

mkdir -p images/$SLUG
"""

[tasks.preview]
description = "Preview the zenn page"
run = "pnpm zenn preview"
